# -*- coding: utf-8 -*-
"""Student pass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-FmXQux57yfbuJ6e0hEUFKsMt5SQQ48
"""

from google.colab import drive
drive.mount('/content/drive')

file_path="/content/drive/MyDrive/student_exam_data.csv"

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import ( accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score, classification_report )

# Display first 5 rows
df = pd.read_csv(file_path)
print("First 5 Rows:")
print(df.head())

print("\nDataset Info:")
print(df.info())
print("\nMissing Values:")
print(df.isnull().sum())
print("\nDuplicate Records:", df.duplicated().sum())
df = df.drop_duplicates()

print("\nDescriptive Statistics:")
print(df.describe())
print("\nPass/Fail Count:")
print(df['Pass/Fail'].value_counts())

# Pass vs Fail Distribution
plt.figure(figsize=(6,5))
sns.countplot(x='Pass/Fail', data=df)
plt.title("Pass vs Fail Distribution")
plt.show()

# Study Hours Distribution
plt.figure(figsize=(8,5))
sns.histplot(df['Study Hours'], bins=10, kde=True)
plt.title("Study Hours Distribution")
plt.show()

# Final Exam Score Distribution
plt.figure(figsize=(8,5))
sns.histplot(df['Previous Exam Score'], bins=10, kde=True)
plt.title("Previous Exam Score Distribution")
plt.show()

# Study Hours vs Previous Exam Score
plt.figure(figsize=(8,5))
sns.scatterplot( x='Study Hours', y='Previous Exam Score', hue='Pass/Fail', data=df )
plt.title("Study Hours vs Previous Exam Score")
plt.show()

# Boxplot
plt.figure(figsize=(8,5))
sns.boxplot(y=df['Previous Exam Score'])
plt.title("Outlier Detection: Previous Exam Score")
plt.show()

# Correlation Heatmap
plt.figure(figsize=(10,8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

def risk_category(row):
  if (
      row['Study Hours'] < 5 and
      row['Previous Exam Score'] < 60
      ):
    return "High Risk"
  elif (
        row['Study Hours'] < 8 and
        row['Previous Exam Score'] < 75
        ):
      return "Medium Risk"
  else:
        return "Low Risk"
df['Risk_Category'] = df.apply(risk_category, axis=1)
print(df['Risk_Category'].value_counts())

X = df.drop(['Pass/Fail', 'Risk_Category'], axis=1)
y = df['Pass/Fail']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
x_train, X_test, y_train, y_test = train_test_split( X_scaled, y, test_size=0.2, random_state=42 )

model = LogisticRegression()
model.fit(x_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("ROC AUC Score:", roc_auc)

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

print(classification_report(y_test, y_pred))

from sklearn.metrics import roc_curve
fpr, tpr, thresholds = roc_curve(y_test, y_prob)
plt.figure(figsize=(8,6))
plt.plot(fpr, tpr)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.show()

df.to_csv("cleaned_student_data.csv", index=False)
print("Project Completed Successfully")

import plotly.express as px

filtered_df = df

# Pass vs Fail
fig1 = px.histogram(
    filtered_df,
    x='Pass/Fail',
    color='Pass/Fail',
    title='Pass vs Fail Distribution' )
fig1.show() # Changed from st.plotly_chart(fig1)

# Study Hours Analysis
fig2 = px.scatter(
    filtered_df,
    x='Study Hours',
    y='Previous Exam Score',
    color='Pass/Fail',
    title='Study Hours vs Previous Exam Score' )
fig2.show() # Changed from st.plotly_chart(fig2)

import plotly.express as px

# Define filtered_df. Assuming it should be the main dataframe if no specific filtering logic is provided.
filtered_df = df

# Attendance Analysis
fig3 = px.scatter(
    filtered_df,
    x='Study Hours', # Corrected column name from 'Attendance_Rate'
    y='Previous Exam Score', # Corrected column name from 'Final_Exam_Score'
    color='Pass/Fail',
    title='Study Hours vs Previous Exam Score' )
fig3.show() # Changed from st.plotly_chart(fig3) for Colab environment

# Risk Category
fig4 = px.pie(
    filtered_df,
    names='Risk_Category',
    title='Student Risk Categories' )
fig4.show() # Changed from st.plotly_chart(fig4) for Colab environment
# st.success("Dashboard Loaded Successfully") # Commented out as 'st' is not defined in this Colab context